services:
  vocitrainer-dev:
    build:
      context: $PWD/../
      dockerfile: $PWD/Dockerfile
    ports:
      - "51337:51337"
    environment:
      PYTHONPATH: ./src
      chatbase_api_key: $CHATBASE_API_KEY
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "51337",
        "--reload",
      ]
