version: "4"
# OPTIMIZE: use docker compose instead of `run-locally.sh`

services:
  vocitrainer-dev:
    build:
      context: $PWD/../
      dockerfile: $PWD/Dockerfile
    ports:
      - "51337:51337"
    environment:
      PYTHONPATH: ./src
      analytics_api_url: "empty"
      feedback_api_url: "https://dev-bitmark-api.taskbase.com"
      api_key: $VOCABTRAINER_API_KEY
      tenant_id: "99"
      vocabtrainer_user: $VOCABTRAINER_USER

    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "51337",
        "--reload",
      ]
